### ISSUE TITLE
No -e option for awk

### ISSUE THREAD

**Issue by wleoncio** [mbant/BayesSUR#1]
L5 of https://github.com/mbant/BayesSUR/blob/master/BayesSUR/configure.ac currently reads the following:

    AC_INIT(BayesSUR, m4_esyscmd_s([awk -e '/^Version:/ {print $2}' DESCRIPTION]))

I couldn't find any reference to this `-e` option on `man awk` (currently running mawk version 1.3.3). This causes a `R CMD check --as-cran` on the built tarball to yield the expected warning

      Output from running autoreconf:
      awk: not an option: -e

I couldn't find any reference to this `e` switch at https://invisible-island.net/mawk/#history so I don't know what could replace it. However, I tried removing it from the `configure.ac` file and now the package checks without warnings.

**My question is: is it safe to remove `-e`?**

For what it's worth, running `awk '/^Version:/ {print $2}' BayesSUR/DESCRIPTION` on the command line returns the version number. I hope that's the value expected to be passed to `m4_esyscmd_s`.

**Comment by mbant** [comment]
> For what it's worth, running awk '/^Version:/ {print $2}' BayesSUR/DESCRIPTION on the command line returns the version number. I hope that's the value expected to be passed to m4_esyscmd_s

Yes that was the idea. I don't think we run into the same `R CMD check` warning, but I agree that it's probably safe to remove.

Unless @zhizuio has any problem with that ofc.

**Comment by wleoncio** [comment]
Great, I'm meeting @zhizuio early next week to go through these minor issues. He told me he was getting a clean check as well, so I'm a bit puzzled about my different results. I am hopeful they might help solve the compiling issues on CRAN's side, though.

I have a pull request with this awk fix as well as some minor refactoring suggestions I needed to make to get a clean check on my machines (Ubuntu LTS and Manjaro). I'm planning on submitting it soon after the meeting next week, so as far as I'm concerned, this issue may soon be ready for closure. :+1:

**Comment by mbant** [comment]
Great, thanks! I won't touch it till your PR then!

**Comment by mbant** [comment]
Solved by [your PR](https://github.com/mbant/BayesSUR/pull/2), I'm closing this
