### ISSUE TITLE
plotMCMCdiag() example not functional

### ISSUE THREAD

**Issue by wleoncio** [mbant/BayesSUR#3]
The [example for the `plotMCMCdiag` function](
https://github.com/mbant/BayesSUR/blob/master/BayesSUR/man/plotMCMCdiag.Rd) currently contains the following call to the `BayesSUR` function:

```
fit <- BayesSUR(Y = example_eQTL[["blockList"]][[1]], 
                X = example_eQTL[["blockList"]][[2]],
                data = example_eQTL[["data"]], outFilePath = tempdir(),
                nIter = 100, burnin = 0, nChains = 2, gammaPrior = "hotspot",
                hyperpar = hyperpar, tmpFolder = "tmp/" )
```

Notice how `nIter = 100`. Now consider the next part of the example:

```
## check output
# show the diagnosis plots with at least 2000*(nbloc+1) iterations where nbloc=3 by default
\donttest{
plotMCMCdiag(fit)
}
```

Since the call to the target-function is wrapped inside a `\donttest{}` macro, it passes the default R check test. However, if one runs `R CMD check --run-donttest`, the test fails. This seems to be caused by the [very first line of the code of `plotMCMCdiag`](https://github.com/mbant/BayesSUR/blob/master/BayesSUR/R/plotMCMCdiag.R), which triggers a stop under the condition of `object$input$nIter < 4000`. This seems to be inconsistent with the comment in the block above, which as I understand says there are diagnosis plots with at least 8000 iterations (considering the default of `nbloc=3`.

The example works by changing the last part to the following:

```
\donttest{
fit2 <- BayesSUR(Y = example_eQTL[["blockList"]][[1]],  
                 X = example_eQTL[["blockList"]][[2]], 
                 data = example_eQTL[["data"]],
                 outFilePath = tempdir(), 
                 nIter = 4000, burnin = 0, nChains = 2,
                 gammaPrior = "hotspot", 
                 hyperpar = hyperpar, tmpFolder = "tmp/") 
plotMCMCdiag(fit2)
}
```

This is still justifiably wrapped inside  `\donttest{}` because it takes a long time to run, but it runs fine since `nIter >= 4000`. Is this the correct procedure or should the code of `plotMCMCdiag()` be modified to allow `fit` to also generate diagnostic plots?

**Comment by mbant** [comment]
> Is this the correct procedure or should the code of plotMCMCdiag() be modified to allow fit to also generate diagnostic plots?

@zhizuio authored those R functions, so I'd wait for him to answer before accepting, but I agree we could just up the `nIter` to 4000 as long as it's wrapped in a `\donttest{}`.

**Comment by zhizuio** [comment]
I will modify the code of plotMCMCdiag() to allow it for any iterations tomorrow.

Best,
George

On 4 Dec 2019, at 18:47, Marco Banterle <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this the correct procedure or should the code of plotMCMCdiag() be modified to allow fit to also generate diagnostic plots?
@zhizuio<https://github.com/zhizuio> authored those R functions, so I'd wait for him to answer before accepting, but I agree we could just up the nIter to 4000 as long as it's wrapped in a \donttest{}.

**Comment by zhizuio** [comment]
I have modified the function plotMCMCdiag() to allow any more than one MCMC iteration.

**Comment by mbant** [comment]
Great, thanks!
Solved by [this commit](https://github.com/mbant/BayesSUR/commit/e8130a96c7be8d7a7e74908a5b051a1900fdace0)
