### ISSUE TITLE
CPU / elapsed times ratio > 2.5s

### ISSUE THREAD

**Issue by zhizuio** [mbant/BayesSUR#4]
**CRNA submission check NOTE**
[https://win-builder.r-project.org/incoming_pretest/BayesSUR_2.1-4_20230824_183212/Debian/00check.log](url)

Flavor: r-devel-linux-x86_64-debian-gcc
Check: examples, Result: NOTE
 Examples with CPU (user + system) or elapsed time > 5s
                user system elapsed
 plot.BayesSUR 8.208   0.31   0.285
 Examples with CPU time > 2.5 times elapsed time
                   user system elapsed  ratio
 plotMCMCdiag     2.531  0.095   0.082 32.024
 summary.BayesSUR 3.101  0.094   0.100 31.950
 plotManhattan    3.503  0.096   0.113 31.850
 plotEstimator    3.520  0.151   0.121 30.339
 plot.BayesSUR    8.208  0.310   0.285 29.888
 elpd             2.182  0.081   0.084 26.940
 getEstimator     2.124  0.099   0.085 26.153
 predict.BayesSUR 3.080  0.122   0.123 26.033
 plotNetwork      3.206  0.121   0.130 25.592
 print.BayesSUR   1.508  0.019   0.071 21.507
 plotGraph        1.494  0.042   0.075 20.480
 fitted.BayesSUR  1.687  0.067   0.098 17.898
 BayesSUR         3.193  0.225   0.219 15.607
 coef.BayesSUR    1.350  0.075   0.096 14.844
 plotCPO          1.266  0.030   0.088 14.727

**Comment by wleoncio** [comment]
Couldn't manage to reproduce this in local, `rhub::check_for_cran()` or `devtools::check_win_*()`. I also couldn't find the issue on the package [CRAN ckecks page](https://cran.r-project.org/web/checks/check_results_BayesSUR.html), ~~perhaps something not worth worrying about?~~

Edit: just remembered/noticed this is a pre-release CRAN check, so we _should_ pay attention to it.

**Comment by wleoncio** [comment]
[This conversation](https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008610.html) suggests the error is related to the use of _more_ than 2 threads per worker. I noticed that in the package `maxThreads` defaults to 1 on `BayesSUR()` and to 2 on `BayesSur_internal()`. Any reason for that difference? Even though that's technically withing the aforementioned limit of 2 cores, perhaps setting the default to 1 across the package solves the issue (not to mention a more predictive behavior w.r.t. parallelization).

**Comment by zhizuio** [comment]
I do not think there is a special reason with `maxThreads=2` in `BayesSur_internal()`. I can change it to 1. I am also thinking to disable `omp` in C++ when `maxThreads=1`.

**Comment by wleoncio** [comment]
Sounds good! Otherwise, we could consider further recuding the CPU time of the examples (though I understand there's already been optimization in that regard). According to the linked post and the [R internals](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Tools) doc, the `_R_CHECK_EXAMPLE_TIMING_CPU_TO_ELAPSED_THRESHOLD_` variable only considers examples with CPU time longer than 1 second.

**Comment by zhizuio** [comment]
New version is on its way to CRAN now:-) 
We have now `maxThreads=1` on `BayesSur_internal()`  in which case specifying `omp_set_num_threads(1)` in C++. Previously there was only `omp_set_num_threads(maxThreads)` if `maxThreads>1` (not strict logic).
